### ISSUE TITLE
破解版配置文件

### ISSUE THREAD

**Issue by dfhs-oss** [daxuanzi515/CodeReview#6]
您好，test分支里未找到破解版`config.ini`，请问是否可以麻烦您提供一下？拜托了万分感谢
![QQ截图20240703153348](https://github.com/daxuanzi515/CodeReview/assets/174589549/726a6a84-83fe-4e4f-b307-4f47fb31cae4)
![QQ截图20240703153640](https://github.com/daxuanzi515/CodeReview/assets/174589549/d5b3bfea-7ffd-4289-a563-dc28f304b544)

**Comment by daxuanzi515** [comment]
test/config_.ini

**Comment by dfhs-oss** [comment]
万分感谢！祝学业有成/工作顺利！发自我的 iPhone在 2024年8月7日，19:50，daxuanzi515 ***@***.***> 写道：﻿
test/config_.ini
